Allow configuration of Prometheus hostname
moleculerjs/moleculer-metrics pull request #47
Opened 2021-01-05 16:31 UTC by NickClark

In some cases it is necessary to expose the server on more than just localhost. This adds a configuration for exactly that.

2021-01-05 19:12 UTC, NickClark commented
@icebob I think this should be ready to go

2021-01-09 15:53 UTC, icebob requested changes
Please use "0.0.0.0" as the default value for backward compatibility because it's the default in the Node HTTP server.

2021-01-10 04:29 UTC, NickClark commented
I can certainly do that... the reason I had `localhost` default was because that's what it was before. In fact the motivation for this commit was so that I could use `0.0.0.0`. It appeared that Polka used `localhost` by default? Am I wrong?

2021-01-18 16:27 UTC, icebob commented
If you see the default host setting in the Node HTTP server, the host is `0.0.0.0` and polka use it, as well. So if you change it to `localhost` as default, it can cause breaking change.

2023-03-17 18:13 UTC, closed without merging